#!/usr/bin/python3
import os
import argparse


parser = argparse.ArgumentParser(description="Download a folder from Github.")
parser.add_argument('link', metavar='L', type=str, nargs=1, help="A variable to store the link")

args = parser.parse_args()
link = args.link[0]
link = link.replace("https://github.com/", "").replace("tree/", "")
# numixproject/numix-icon-theme/master/Numix-Light

split = link.split("/")
rest = "/".join(split[3:])
os.system(f"curl https://codeload.github.com/{split[0]}/{split[1]}/tar.gz/{split[2]} | tar -xz --strip=2 {split[1]}-{split[2]}/{rest}")
