#!/usr/bin/python
import os
modified = 0
for file in os.listdir(os.getcwd()):
    split1 = file.split("-")
    if len(split1) < 2:
        continue
    split2 = ''.join(split1[1:]).split(".")
    if len(split2) != 2:
        continue
    os.replace(file, split1[0] + '.' + split2[1])
    modified += 1
print("Modified", modified, "files.")
